services:
   mssql:
     image: mcr.microsoft.com/mssql/server:2022-latest
     container_name: jp_sql_container
     environment:
       - ACCEPT_EULA=Y
       - MSSQL_SA_PASSWORD=JobPortal123
       - MSSQL_PID=Express
     ports:
       - "1433:1433"  
     volumes:
       - jp_sql_data:/var/opt/mssql  
   redis:
      image: redis:latest
      container_name: jp_redis_container
      ports:
        - "6379:6379"
      volumes:
        - jp_redis_data:/data
   rabbitmq:
    image: rabbitmq:3-management
    container_name: jp_rabbitmq_container
    environment:
      - RABBITMQ_DEFAULT_USER=Jpa12345
      - RABBITMQ_DEFAULT_PASS=Jpa12345
    ports:
      - "5672:5672"    
      - "15672:15672"  
    volumes:
      - jp_rabbitmq_data:/var/lib/rabbitmq

volumes:
   jp_sql_data:
     driver: local
   jp_redis_data:
      driver: local
   jp_rabbitmq_data:
    driver: local